version: "3"
services:
  nginx:
    image: nginx:1.14.0-alpine-perl
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/etc/conf.d:/etc/nginx/conf.d:ro"
    environment:
      TZ: 'Asia/Shanghai'
    links:
      - mysql:mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.21
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/etc/my.cnf:/etc/mysql/my.cnf:ro"
      - "./mysql/data:/var/lib/mysql"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '' 
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/data:/var/lib/mongo"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
